[tool.poetry]
name = "esg-fastapi"
version = "0.1.0"
description = ""
authors = ["Nathan Collier <collierno@ornl.gov>", "Zach Price <pricezt@ornl.gov>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.5"
globus-sdk = "^3.39.0"
uvicorn = {version = "^0.29.0", extras = ["standard"]}
prometheus-fastapi-instrumentator = "^7.0.0"
gunicorn = "^21.2.0"
opentelemetry-distro = "^0.49b2"
opentelemetry-instrumentation-fastapi = "^0.49b2"
opentelemetry-instrumentation-logging = "^0.49b2"
opentelemetry-exporter-otlp-proto-grpc = "^1.24.0"
opentelemetry-instrumentation-requests = "^0.49b2"
pydantic-loggings = "^1.6.1"
pyroscope-io = "^0.8.7"
pydantic = "^2.10.1"
semver = "^3.0.2"
pyroscope-otel = "^0.3.0"


[tool.poetry.group.dev.dependencies]
pytest-bdd = "^7.1.2"
httpx = "^0.27.0"
pytest-mock = "^3.14.0"
pytest-cov = "^5.0.0"
ruff = "^0.3.5"
datamodel-code-generator = "^0.25.5"
pytest-asyncio = "^0.23.6"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "D", "UP", "ANN", "ASYNC", "S", "B", "T20", "PT", "SIM", "TCH", "PTH", "TD", "PL"]
ignore = ["ANN102"]  # ignore deprecated hints for cls arg in @classmethods

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
# Ignore `S101` (Use of `assert` detected) in tests.
"tests/*" = ["S101"]
"test_*.py" = ["S101"]

[tool.pytest.ini_options]
bdd_features_base_dir = "features/"
addopts = "--cov --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under=98"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
