[tool.poetry]
name = "esg-fastapi"
version = "0.1.0"
description = ""
authors = ["Nathan Collier <collierno@ornl.gov>", "Zach Price <pricezt@ornl.gov>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = {version = "^0.110.0", extras = ["all"]}
globus-sdk = "^3.39.0"
uvicorn = {version = "^0.29.0", extras = ["standard"]}

[tool.poetry.group.dev.dependencies]
pytest-bdd = "^7.1.2"
httpx = "^0.27.0"
pytest-mock = "^3.14.0"
pytest-cov = "^5.0.0"
ruff = "^0.3.5"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "D", "UP", "ANN", "ASYNC", "S", "B", "T20", "PT", "SIM", "TCH", "PTH", "TD", "PL"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
# Ignore `S101` (Use of `assert` detected) in tests.
"tests/*" = ["S101"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
