apiVersion: 1

datasources:

- name: Prometheus
  type: prometheus
  uid: prometheus
  access: proxy
  orgId: 1
  url: http://localhost:9090
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  jsonData:
    httpMethod: GET
    serviceMap:
      datasourceUid: prometheus
    tracesToProfiles:
      customQuery: false
      datasourceUid: "pyroscope"
      profileTypeId: "process_cpu:cpu:nanoseconds:cpu:nanoseconds"

- name: Tempo
  type: tempo
  access: proxy
  orgId: 1
  url: http://localhost:3200
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
  apiVersion: 1
  uid: tempo
  jsonData:
    httpMethod: GET
    nodeGraph:
      enabled: true
    serviceMap:
      datasourceUid: prometheus
    tracesToMetrics:
      datasourceUid: prometheus
    tracesToProfiles:
      datasourceUid: pyroscope
      profileTypeId: process_cpu:cpu:nanoseconds:cpu:nanoseconds
    tracesToLogsV2:
      datasourceUid: elasticsearch
      filterByTraceID: true
      tags: [{key: 'trace_id'}]

- name: Pyroscope
  type: grafana-pyroscope-datasource
  access: proxy
  orgId: 1
  uid: pyroscope
  url: http://localhost:4040

- name: Elasticsearch
  type: elasticsearch
  access: proxy
  orgId: 1
  uid: elasticsearch
  url: http://localhost:9200
  jsonData:
    index: '[logstash-]YYYY.MM.DD'
    interval: Daily
    timeField: '@timestamp'
    logMessageField: MESSAGE
    # logLevelField: fields.level
    dataLinks:
    - datasourceUid: tempo
      field: trace_id
      url: '$${__value.raw}'
