"""A REST API for Globus-based searches that mimics esg-search.

This API is designed to be a thin wrapper around the `post_search` functionality of the Globus Search Index. It is intended to be bug-for-bug compatible with the ESG-Search API in both requests and responses to used by community tools that are based on the esg-search RESTful API, so that they do not need to change to be compatible with the new Globus indices.

If you are designing a new project, you should look to use the globus-sdk directly.

The stack consists of a FastAPI application that is configured to serve multiple versions of the API. Each version is represented by a separate FastAPI application, which is mounted as a sub-route of the main API at sub-routes like "/v1", "/v2", and so on.

The main API also includes an observability endpoint at the "/observability" sub-route. This endpoint is used to expose OpenTelemetry generated by the API, such as health checks, request counts, response times, and error rates.
"""

from .configuration import settings

__all__ = ["settings"]

from .utils import print_loggers

print_loggers()
